// Original hand-authored pixel-art sprites (character grids rendered as SVG
// rects by PixelSprite). No external art assets, no third-party sprite
// sheets — every icon here is defined inline as data.

export type PixelGrid = string[];

export const ICONS: Record<string, PixelGrid> = {
  earth: [
    "..BBBBBB..",
    ".BBBBBBBB.",
    "BBGGBBGGBB",
    "BGGGBBBGGB",
    "BBBGGGGBBB",
    "BBGGBBGGBB",
    "BGGBBBBGGB",
    "BBBGGGGBBB",
    ".BBBBBBBB.",
    "..BBBBBB..",
  ],
  cloud: [
    "...WWWW...",
    "..WWWWWWW.",
    ".WWWWWWWWW",
    "WWWWWWWWWW",
    ".WWWWWWWWW",
    "..WWWWWW..",
  ],
  tree: [
    ".....G.....",
    "....GGG....",
    "...GGGGG...",
    "..GGGGGGG..",
    "....GGG....",
    "...GGGGG...",
    ".....O.....",
    ".....O.....",
  ],
  mountain: [
    ".......Y........",
    "......YWY.......",
    ".....D...D......",
    "....D.....D.....",
    "...D...Y...D....",
    "..D...YWY...D...",
    ".D....D.D....D..",
    "DDDDDDDDDDDDDDDD",
  ],
  droplet: [
    "....B.....",
    "...BBB....",
    "..BBBBB...",
    ".BBBBBBB..",
    ".BBBBBBB..",
    "..BBBBB...",
    "...BBB....",
  ],
  sun: [
    "....Y....",
    "Y..YYY..Y",
    "..YYYYY..",
    ".YYYYYYY.",
    "YYYYYYYYY",
    ".YYYYYYY.",
    "..YYYYY..",
    "Y..YYY..Y",
    "....Y....",
  ],
  star: [
    "....Y....",
    "....Y....",
    "..Y.Y.Y..",
    "...YYY...",
    "YYYYYYYYY",
    "...YYY...",
    "..Y.Y.Y..",
    "....Y....",
    "....Y....",
  ],
  notebook: [
    "KKKKKKKK",
    "KWWWWWWK",
    "KWKKKKWK",
    "KWKKKKWK",
    "KWKKKKWK",
    "KWKKKKWK",
    "KWWWWWWK",
    "KKKKKKKK",
  ],
  telescope: [
    "........KK",
    ".......KKK",
    "......KKK.",
    ".....KKK..",
    "....KKK...",
    "...KKK....",
    "..KKO.....",
    ".KK.......",
  ],
  satellite: [
    "W...KK...W",
    "WW..KK..WW",
    ".W..KK..W.",
    "..KKKKKK..",
    "..KWWWWK..",
    "..KKKKKK..",
    ".W..KK..W.",
    "WW..KK..WW",
  ],
  compass: [
    "...YYY...",
    ".Y.....Y.",
    "Y...C...Y",
    "Y..CKC..Y",
    "Y...C...Y",
    ".Y.....Y.",
    "...YYY...",
  ],
  wave: [
    "..BB..BB..BB..",
    ".B..BB..BB..B.",
    "B....BB....B..",
  ],
  magnifier: [
    "..KKKK...",
    ".K....K..",
    "K......K.",
    "K..GG..K.",
    "K..GG..K.",
    "K......K.",
    ".K....K..",
    "..KKKK.K.",
    ".......KK",
  ],
  chart: [
    "K........",
    "K........",
    "K..G.....",
    "K..G..Y..",
    "K..G..Y.C",
    "K..G..Y.C",
    "K..G..Y.C",
    "KKKKKKKKK",
  ],
  scales: [
    "....K....",
    "....K....",
    "KKKKKKKKK",
    "B.......C",
    "BB.....CC",
    ".........",
    "....K....",
    "...KKK...",
  ],
  pin: [
    "..YYYY...",
    ".Y....Y..",
    "Y..KK..Y.",
    "Y..KK..Y.",
    ".Y....Y..",
    "..YYYY...",
    "...YY....",
    "....Y....",
  ],
  link: [
    ".GGG...........",
    "G...G..........",
    "G...G..GGG.....",
    ".GGG..G...G....",
    ".......G...G...",
    "........GGG....",
  ],
  scroll: [
    ".YYYYYYYY.",
    "YWWWWWWWWY",
    "YWKKKKKKWY",
    "YWKKKKKKWY",
    "YWWWWWWWWY",
    "YWKKKKKKWY",
    "YWWWWWWWWY",
    ".YYYYYYYY.",
  ],
  flag: [
    "K.........",
    "KCCCCC....",
    "KCWCCC....",
    "KCCCCC....",
    "KCWCCC....",
    "KCCCCC....",
    "K.........",
    "K.........",
    "K.........",
  ],
  // Sector icons for the cause / impact / action view (components/change/ImpactChain.tsx).
  crop: [
    "...Y..Y...",
    "..YY..YY..",
    "...Y..Y...",
    "..YY..YY..",
    "...Y..Y...",
    "...G..G...",
    "...G..G...",
    "...G..G...",
  ],
  health: [
    "...CCC...",
    "...CCC...",
    "CCCCCCCCC",
    "CCCCCCCCC",
    "CCCCCCCCC",
    "...CCC...",
    "...CCC...",
  ],
  house: [
    "....C....",
    "...CCC...",
    "..CCCCC..",
    ".CCCCCCC.",
    "..OOOOO..",
    "..OKOOO..",
    "..OKOOO..",
  ],
  bolt: [
    "....YY.",
    "...YY..",
    "..YY...",
    ".YYYYY.",
    "...YY..",
    "..YY...",
    ".Y.....",
  ],
  snow: [
    "...B...",
    ".B.B.B.",
    "..BBB..",
    "BBBBBBB",
    "..BBB..",
    ".B.B.B.",
    "...B...",
  ],
};

export const PIXEL_COLOR_VARS: Record<string, string> = {
  B: "var(--app-accent-sky)",
  G: "var(--app-accent-green)",
  D: "var(--app-accent-green-dark)",
  Y: "var(--app-accent-gold)",
  O: "var(--app-accent-gold-dark)",
  W: "var(--app-panel)",
  K: "var(--app-ink)",
  C: "var(--app-accent-clay)",
};
