"""add watches table

Revision ID: 22d18092431f
Revises: 82668380a0c2
Create Date: 2026-09-23 18:48:00.760383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d18092431f'
down_revision: Union[str, None] = '82668380a0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watches',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('region_code', sa.String(length=64), nullable=False),
    sa.Column('variable_code', sa.String(length=64), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_investigation_id', sa.UUID(), nullable=True),
    sa.Column('last_finding_id', sa.UUID(), nullable=True),
    sa.Column('last_trend_per_year', sa.Float(), nullable=True),
    sa.Column('last_significance', sa.String(length=32), nullable=True),
    sa.Column('last_check_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watches_due', 'watches', ['is_active', 'next_check_at'], unique=False)
    op.create_index(op.f('ix_watches_user_id'), 'watches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watches_user_id'), table_name='watches')
    op.drop_index('ix_watches_due', table_name='watches')
    op.drop_table('watches')
    # ### end Alembic commands ###
