"""initial schema

Revision ID: 4952c91c3648
Revises: 
Create Date: 2026-09-23 01:34:03.157737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4952c91c3648'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The postgis/postgis Docker image (local dev, CI) ships with this already
    # enabled; a fresh hosted database (Supabase, ...) does not, and the
    # `regions.geom` column below fails without it. No-op where it exists.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requires_credentials', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_code'), 'datasets', ['code'], unique=True)
    op.create_table('nasa_query_cache',
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('dataset_code', sa.String(length=64), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nasa_query_cache_cache_key'), 'nasa_query_cache', ['cache_key'], unique=True)
    op.create_table('regions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('min_lat', sa.Float(), nullable=False),
    sa.Column('max_lat', sa.Float(), nullable=False),
    sa.Column('min_lon', sa.Float(), nullable=False),
    sa.Column('max_lon', sa.Float(), nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=False),
    sa.Column('centroid_lon', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: no explicit CREATE INDEX for `geom` here — GeoAlchemy2 registers a
    # DDL event that creates the GiST spatial index automatically right after
    # CREATE TABLE, so an explicit op.create_index for it would collide.
    op.create_index(op.f('ix_regions_code'), 'regions', ['code'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('investigations',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variables',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('units', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('valid_min', sa.Float(), nullable=True),
    sa.Column('valid_max', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'code', name='uq_dataset_variable')
    )
    op.create_index(op.f('ix_variables_code'), 'variables', ['code'], unique=False)
    op.create_table('analysis_results',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('variable_id', sa.UUID(), nullable=True),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=128), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('variable_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('what', sa.Text(), nullable=False),
    sa.Column('where', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('trend_per_year', sa.Float(), nullable=False),
    sa.Column('trend_units', sa.String(length=64), nullable=False),
    sa.Column('total_change', sa.Float(), nullable=False),
    sa.Column('percent_change', sa.Float(), nullable=True),
    sa.Column('statistical_method', sa.String(length=128), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=False),
    sa.Column('confidence_interval', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('significance_classification', sa.String(length=32), nullable=False),
    sa.Column('importance_note', sa.Text(), nullable=False),
    sa.Column('data_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spatial_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('robustness', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('narrative_source', sa.String(length=32), nullable=False),
    sa.Column('discovery_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_findings_variable_region', 'findings', ['variable_id', 'region_id'], unique=False)
    op.create_table('investigation_steps',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_steps_investigation_seq', 'investigation_steps', ['investigation_id', 'seq'], unique=False)
    op.create_table('observations',
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('variable_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_observations_investigation', 'observations', ['investigation_id'], unique=False)
    op.create_table('provenance',
    sa.Column('finding_id', sa.UUID(), nullable=True),
    sa.Column('investigation_id', sa.UUID(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('variable_id', sa.UUID(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=True),
    sa.Column('retrieval_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_method', sa.Text(), nullable=False),
    sa.Column('statistical_method', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_by', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visualizations',
    sa.Column('finding_id', sa.UUID(), nullable=True),
    sa.Column('investigation_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visualizations')
    op.drop_table('reports')
    op.drop_table('provenance')
    op.drop_index('ix_observations_investigation', table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_steps_investigation_seq', table_name='investigation_steps')
    op.drop_table('investigation_steps')
    op.drop_index('ix_findings_variable_region', table_name='findings')
    op.drop_table('findings')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_variables_code'), table_name='variables')
    op.drop_table('variables')
    op.drop_table('investigations')
    op.drop_table('users')
    op.drop_index(op.f('ix_regions_code'), table_name='regions')
    op.drop_index('idx_regions_geom', table_name='regions', postgresql_using='gist')
    op.drop_table('regions')
    op.drop_index(op.f('ix_nasa_query_cache_cache_key'), table_name='nasa_query_cache')
    op.drop_table('nasa_query_cache')
    op.drop_index(op.f('ix_datasets_code'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
