"""add skeptic review to findings

Revision ID: 82668380a0c2
Revises: 893a3491aa00
Create Date: 2026-09-23 11:45:03.558441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82668380a0c2'
down_revision: Union[str, None] = '893a3491aa00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('skeptic_review', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'skeptic_review')
    # ### end Alembic commands ###
