import { CONCERN_LABEL, SECTOR_LABEL, isHarmful } from "./insightView";
import type { FindingDetail } from "./types";

export function downloadTextFile(filename: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function slug(finding: FindingDetail): string {
  return `${finding.variable_code}_${finding.region_code}_${finding.period_start}_${finding.period_end}`.toLowerCase();
}

/** The annual observation + fitted-trend series, as CSV — the exact numbers
 * behind the time series chart, nothing recomputed or rounded differently. */
export function findingToCsv(finding: FindingDetail): string {
  const ts = finding.visualizations.timeseries;
  if (!ts) return "year,observed\n";
  const fittedByYear = new Map(ts.trend_line.map((p) => [p.year, p.fitted]));
  const rows = ts.points.map((p) => {
    const fitted = fittedByYear.get(p.year);
    return `${p.year},${p.value},${fitted !== undefined ? fitted.toFixed(6) : ""}`;
  });
  return [`year,observed_${finding.variable_code},fitted_trend`, ...rows].join("\n") + "\n";
}

export function findingCsvFilename(finding: FindingDetail): string {
  return `${slug(finding)}_timeseries.csv`;
}

/** A self-contained Markdown scientific report — every field traces
 * directly to the Finding record, nothing added or reworded here. */
export function findingToMarkdownReport(finding: FindingDetail): string {
  const lines: string[] = [];
  lines.push(`# ${finding.title}`);
  lines.push("");
  lines.push(`**Generated by AtmoSpy** — ${new Date().toISOString().slice(0, 10)}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`| | |`);
  lines.push(`|---|---|`);
  lines.push(`| **WHAT** | ${finding.what} |`);
  lines.push(`| **WHERE** | ${finding.where} |`);
  lines.push(`| **WHEN** | ${finding.period_start} to ${finding.period_end} |`);
  lines.push(`| **HOW MUCH** | ${finding.trend_per_year.toFixed(4)} ${finding.trend_units} (${finding.percent_change !== null ? `${finding.percent_change > 0 ? "+" : ""}${finding.percent_change.toFixed(1)}%` : "n/a"} total) |`);
  lines.push(`| **SIGNIFICANCE** | ${finding.significance_classification.replace("_", " ")} (p = ${finding.p_value.toFixed(4)}) |`);
  lines.push(`| **METHOD** | ${finding.statistical_method} |`);
  lines.push("");
  lines.push("## Interpretation");
  lines.push("");
  lines.push(finding.interpretation);
  lines.push("");
  lines.push(`*Narrative source: ${finding.narrative_source === "llm" ? "GPT-OSS-120B (Groq)" : "deterministic template"}*`);
  lines.push("");
  lines.push("## Limitations");
  lines.push("");
  lines.push(finding.limitations);
  lines.push("");

  const insight = finding.insight;
  if (insight) {
    lines.push("## Level of concern, possible drivers, impacts and actions");
    lines.push("");
    lines.push(`**Level of concern:** ${CONCERN_LABEL[insight.concern]} · **Confidence in the finding:** ${insight.confidence}`);
    lines.push("");
    const section = (title: string, items: string[]) => {
      if (items.length === 0) return;
      lines.push(`**${title}**`);
      for (const t of items) lines.push(`- ${t}`);
      lines.push("");
    };
    if (insight.applicable) {
      lines.push(insight.headline);
      lines.push("");
      section("Possible drivers (general context)", insight.drivers.map((d) => `${d.title}: ${d.text}`));
      section("What it could mean", insight.impacts.map((i) => `${SECTOR_LABEL[i.sector] ?? i.sector}: ${i.text}`));
      section(isHarmful(insight.concern) ? "Reduce the cause" : "Limit the cause", insight.mitigate);
      section("Cope with the effect", insight.adapt);
    } else {
      lines.push(insight.concern_reasons.join(" "));
      lines.push("");
    }
    section("What this finding's own data adds", insight.evidence.map((e) => e.text));
    lines.push(`*${insight.disclaimer}*`);
    lines.push("");
    lines.push("Sources: " + insight.references.map((r) => `[${r.label}](${r.url})`).join("; "));
    lines.push("");
  }

  if (finding.related_variables && finding.related_variables.length > 0) {
    lines.push("## Related variables (correlation, not causation)");
    lines.push("");
    for (const rv of finding.related_variables) {
      lines.push(`- **${rv.variable_name}**: ${rv.method} r = ${rv.r.toFixed(2)}, p = ${rv.p_value.toFixed(4)} (n=${rv.n})`);
    }
    lines.push("");
  }

  if (finding.robustness) {
    lines.push("## Robustness check");
    lines.push("");
    lines.push(`Verdict: **${finding.robustness.verdict}**`);
    for (const c of finding.robustness.caveats) lines.push(`- ${c}`);
    lines.push("");
  }

  if (finding.provenance) {
    lines.push("## Data provenance");
    lines.push("");
    lines.push(`- **Source**: ${finding.provenance.source_name}${finding.provenance.dataset_version ? ` (v${finding.provenance.dataset_version})` : ""}`);
    lines.push(`- **Processing**: ${finding.provenance.processing_method}`);
    lines.push(`- **Retrieved**: ${finding.provenance.retrieval_time}`);
    lines.push(`- **Query**: ${finding.provenance.url}`);
    lines.push("");
  }

  const sourceName = finding.provenance?.source_name ?? "NASA data";
  lines.push("---");
  lines.push(`*Not an official NASA product. Every number above comes from deterministic Python statistics run on real ${sourceName} — see the full methodology at /about.*`);

  return lines.join("\n");
}

export function findingReportFilename(finding: FindingDetail): string {
  return `${slug(finding)}_report.md`;
}

export function findingToBibtex(finding: FindingDetail): string {
  const year = new Date().getFullYear();
  const key = `atmospy${year}${finding.variable_code.toLowerCase()}${finding.region_code.replace(/_/g, "")}`;
  const sourceName = finding.provenance?.source_name ?? "NASA data";
  return [
    `@misc{${key},`,
    `  title = {${finding.title}},`,
    `  author = {{AtmoSpy}},`,
    `  year = {${year}},`,
    `  howpublished = {Autonomous analysis of ${sourceName}},`,
    `  note = {Method: ${finding.statistical_method}. Period: ${finding.period_start} to ${finding.period_end}. p = ${finding.p_value.toFixed(4)}.}`,
    `}`,
  ].join("\n");
}
